@RinhaDeBackend2024.Api_HostAddress = http://localhost:6163

POST {{RinhaDeBackend2024.Api_HostAddress}}/clientes/1/transacoes
Accept: application/json
Content-Type: application/json

{
  "valor": 10,
  "tipo": "c",
  "descricao": "teste"
}
###

GET {{RinhaDeBackend2024.Api_HostAddress}}/clientes/1/extrato
Accept: application/json
Keep-Alive: timeout=300, max=1000

###
