FROM ubuntu:latest

EXPOSE 5432

RUN apt-get update && \
    apt-get install -y \
    cmake \
    g++ \
    protobuf-compiler \
    libprotobuf-dev

RUN protoc --version

WORKDIR /app
COPY . .

RUN mkdir -p build && \
    cd build && \
    cmake .. && \
    make

EXPOSE 5432

CMD ["./build/RyansDB"]
